=== trantridue/vente-project/vente.ws/src/test/resources/dtd/vente.dtd
<!ELEMENT dataset (
    user*,
    branch*,
    role*
    )>


<!ELEMENT user EMPTY>
<!ATTLIST user
    id CDATA #REQUIRED
    username CDATA #IMPLIED
    password CDATA #IMPLIED
    phone CDATA #REQUIRED
    firstname CDATA #IMPLIED
    lastname CDATA #IMPLIED
    address CDATA #IMPLIED
    email CDATA #IMPLIED
    is_active CDATA #IMPLIED
    birth_day CDATA #IMPLIED
    date CDATA #IMPLIED
    base_salary CDATA #IMPLIED
    branch_id CDATA #IMPLIED
    role_id CDATA #IMPLIED
>

<!ELEMENT branch EMPTY>
<!ATTLIST branch
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    label CDATA #IMPLIED
    address CDATA #IMPLIED
    date CDATA #IMPLIED
>

<!ELEMENT role EMPTY>
<!ATTLIST role
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    label CDATA #IMPLIED
    description CDATA #IMPLIED
>

=== trantridue/vente-project/vente.logic/src/test/resources/dataset/initDb.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/vente.dtd">
<dataset>
  <branch id="1" name="Shop 1" label="Cửa hàng trung tâm" date="2016-10-10 21:09:09" address="Số 19 Vạn Phúc"/>
  <branch id="2" name="Shop 2" label="Cửa hàng số 2" date="2016-10-10 21:09:09" address="Số 3 Lê Văn Lương - Vạn Phúc"/>
  <branch id="3" name="Shop 3" label="Cửa hàng số 3" date="2016-10-10 21:09:09" address="Số 5 Lê Văn Lương - Vạn Phúc"/>
  
  <role id="1" name="admin" label="Quản trị" description="Quản trị"/>
  <role id="2" name="inputer" label="Nhập liệu" description="Nhập liệu"/>
  <role id="3" name="staft" label="Nhân viên bán hàng" description="bán hàng"/>

  <user id="1" branch_id="1" role_id="1" is_active="1" username="admin" phone="123456789" password="123456" firstname="quan tri" lastname="quan tri" address="van phuc" email="admin@gmail.com" date="2016-06-11 10:10:10" birth_day="1982-06-09" base_salary="3000"/>
  <user id="2" branch_id="2" role_id="2" is_active="1" username="due" phone="123456789" password="11112222" firstname="tran tri due" lastname="quan tri" address="van phuc" email="trantridue@gmail.com" date="2016-06-12 10:10:10" birth_day="1983-06-10" base_salary="3000"/>
  <user id="3" branch_id="3" role_id="3" is_active="1" username="hien" phone="123456789" password="333444" firstname="tran thi thu hien" lastname="quan tri" address="Ha dong" email="htranthithu@gmail.com" date="2016-06-13 10:10:10" birth_day="1984-06-11" base_salary="3000"/>
  <user id="4" branch_id="1" role_id="3" is_active="1" username="linh" phone="123456789" password="55556666" firstname="ta khanh linh" lastname="quan tri" address="van phu" email="linhtk@gmail.com" date="2016-06-14 10:10:10" birth_day="1985-06-12" base_salary="3000"/>
 
</dataset>
